/* eslint-disable import/prefer-default-export */
export const types = {
  FETCH_NOTES_LOADING: 'FETCH_NOTES_LOADING',
  FETCH_NOTES_RESPONSE: 'FETCH_NOTES_RESPONSE',
  ADD_NOTE: 'ADD_NOTE',
  UPDATE_NOTE: 'UPDATE_NOTE',
  DELETE_NOTE: 'DELETE_NOTE',
  ADD_CATEGORY: 'ADD_CATEGORY',
  FETCH_CATEGORY: 'FETCH_CATEGORY',
};
